version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=your_openai_api_key
